In [3]:
# 1. Create a numpy array of integers from 1 to 10 and print its shape, size and data type.
import numpy as np
arr = np.arange(1, 11)
print("Array:", arr)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data Type:", arr.dtype)

Array: [ 1  2  3  4  5  6  7  8  9 10]
Shape: (10,)
Size: 10
Data Type: int64


In [5]:
""" 2. Create a 2D numpy array of shape (3, 3) with values from 1 to 9 and display 
- number of dimensions
- shape
- sum of all elements """

array = np.arange(1, 10).reshape(3, 3)
print(f"Array: {array}")
print(f"Dimensions: {array.ndim}")
print(f"Shape: {array.shape}")
print(f"Sum of elements: {array.sum()}")

Array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimensions: 2
Shape: (3, 3)
Sum of elements: 45


In [ ]:
""" 3. Create an array of 5 zeros and another of 5 ones. Multiply both and display the result."""

arr1 = np.array([0, 0, 0, 0, 0])
arr2 = np.array([1, 1, 1, 1, 1])

prod = np.multiply(arr1, arr2)

print(f"The product is: {prod}")

The product is: [0 0 0 0 0]


In [ ]:
""" 4. Create an array of even numbers between 20 and 40. Use slicing to display the first 3
elements."""

array = np.arange(20, 41, 2) # arange(start, stop, step)
print(array[0:3])

[20 22 24]


In [ ]:
""" 5. Reshape a 1D array of 12 elements into a 3x4 matrix and calculate the sum along axis=0 and
axis=1."""

myArr = np.arange(12)
print(f"1D Array: {myArr}")

newArr = myArr.reshape(3, 4)
print(f"2D Array: \n {newArr}")

print(f" Sum along axis 0 : {newArr.sum(axis=0)}") # sum along y axis
print(f" Sum along axis 1 : {newArr.sum(axis=1)}") # sum along x axis

1D Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
2D Array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
 Sum along axis 0 : [12 15 18 21]
 Sum along axis 1 : [ 6 22 38]


In [ ]:
""" 6. Create a 5x5 identity matrix using NumPy. """
identityMatrix = np.identity(5)
print(identityMatrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
""" 7. Create a 1D array of 10 random integers between 1 and 100. Find the maximum and
minimum values and their indices. """

from numpy import random

a = np.random.randint(1, 101, size=10)
print(f"The Array is {a}")
maxIndex = np.where(a == a.max())
minIndex = np.where(a == a.min())
print(f"The Max Element is {a.max()} at the index {maxIndex[0]} and the Min Element is {a.min()} at the index {minIndex[0]}")

The Array is [16 97 33 76 38 70 30 71 40 79]
The Max Element is 97 at the index [1] and the Min Element is 16 at the index [0]


In [43]:
""" 8. Generate a NumPy array of 6 float numbers between 0 and 1 using linspace. Round the
values to 2 decimal places."""

arr = np.linspace(0, 1, 6)
print(arr)
print(np.round(arr,2))

[0.  0.2 0.4 0.6 0.8 1. ]
[0.  0.2 0.4 0.6 0.8 1. ]


In [45]:
""" 9. Create a NumPy array with some repeated values and remove the duplicates. """
arr = np.array([1, 2, 3, 2, 4, 3, 5, 1, 6])

print(f"Orginal Array: {arr}")
print(f"Unique Array: {np.unique(arr)}")

Orginal Array: [1 2 3 2 4 3 5 1 6]
Unique Array: [1 2 3 4 5 6]


In [ ]:
"""Create two 3x3 matrices and perform the following operations:
● Matrix addition
● Matrix multiplication
● Element-wise multiplication"""

mat1 = np.arange(10, 19).reshape(3, 3)
mat2 = np.arange(25, 34).reshape(3, 3)

print("Matrix 1:\n", mat1)
print("Matrix 2:\n", mat2)

print(f"\nSum:\n{np.add(mat1, mat2)}")
print(f"\nElement Wise Multiplication: \n{np.multiply(mat1, mat2)}")
print(f"\n Matrix Multiplication:\n {np.dot(mat1, mat2)}")


Matrix 1:
 [[10 11 12]
 [13 14 15]
 [16 17 18]]
Matrix 2:
 [[25 26 27]
 [28 29 30]
 [31 32 33]]
Sum:
[[35 37 39]
 [41 43 45]
 [47 49 51]]
Element Wise Multiplication: 
[[250 286 324]
 [364 406 450]
 [496 544 594]]

 Matrix Multiplication:
 [[ 930  963  996]
 [1182 1224 1266]
 [1434 1485 1536]]
