In [6]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [7]:
import numpy as np
a = np.array(92)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [8]:
print(a)
print("Dimension =", a.ndim)

92
Dimension = 0


In [9]:
print(b)
print("Dimension =", b.ndim)

[1 2 3 4 5]
Dimension = 1


In [10]:
#dtype parameter

import numpy as np
a = np.array([1, 2, 3], dtype = float) # float , str

print(a)

[1. 2. 3.]


In [11]:
import numpy as np

c = np.array([[1, 2, 3], [4, 5, 6]])
print("c =" + "\n", c)

c =
 [[1 2 3]
 [4 5 6]]


In [12]:
import numpy as np
x = np.array([11, 12, 13, 14, 15, 60, 70, 80, 90, 100])
print(x)

[ 11  12  13  14  15  60  70  80  90 100]


In [13]:
z = x[np.array([3, 3, 1, 8])] #location values
print(z)

[14 14 12 90]


In [15]:
d = [1, 2, 3, 4, 5]
e = [5, 6, 7, 8, 9]
f = [2, 45, 32, 78, 65]
g = [3, 6, 8, 9, 2]
h = [66, 99, 88, 33, 22]
my_matrices = np.matrix([d, e, f, g, h])
my_matrices

matrix([[ 1,  2,  3,  4,  5],
        [ 5,  6,  7,  8,  9],
        [ 2, 45, 32, 78, 65],
        [ 3,  6,  8,  9,  2],
        [66, 99, 88, 33, 22]])

In [16]:
my_matrices[1:4, 2:5]

matrix([[ 7,  8,  9],
        [32, 78, 65],
        [ 8,  9,  2]])

In [18]:
li = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
ar = np.array(li)
print("list =", li)
print("numpy_array = " + "\n", ar)

list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
numpy_array = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
type(li)

list

In [20]:
type(ar)

numpy.ndarray

In [21]:
li + li

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [22]:
ar + ar

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [24]:
import numpy as np
k = np.array([3, 4, 5, 6, 8])
print(k)

[3 4 5 6 8]


In [27]:
copy1 = k.copy()
view1 = k.view()

k[2] = 90
print(k)
print(f"modified array = {view1}")

[ 3  4 90  6  8]
modified array = [ 3  4 90  6  8]


In [28]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [29]:
print(arr.shape)

(12,)


In [30]:
newarr = arr.reshape(3, 4)
print(newarr)
print(newarr.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [32]:
x = np.linspace(0, 5, 4)
print(x)

[0.         1.66666667 3.33333333 5.        ]


In [33]:
y = np.linspace(0, 16, 5)
print(y)

[ 0.  4.  8. 12. 16.]


In [38]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(a.min())
print(a.max())
print(a.sum())
print(a.std())

1
12
78
3.452052529534663


In [1]:
import numpy as np

x = [1, 2, 3]
print(x, type(x))

[1, 2, 3] <class 'list'>


In [3]:
a = np.asarray(x)
print(a, type(a))

[1 2 3] <class 'numpy.ndarray'>


In [4]:
# Join two arrays
arr = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr, arr2))
print(arr)

[1 2 3 4 5 6]
