In [6]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [7]:
import numpy as np
a = np.array(92)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [8]:
print(a)
print("Dimension =", a.ndim)

92
Dimension = 0


In [9]:
print(b)
print("Dimension =", b.ndim)

[1 2 3 4 5]
Dimension = 1


In [10]:
#dtype parameter

import numpy as np
a = np.array([1, 2, 3], dtype = float) # float , str

print(a)

[1. 2. 3.]


In [11]:
import numpy as np

c = np.array([[1, 2, 3], [4, 5, 6]])
print("c =" + "\n", c)

c =
 [[1 2 3]
 [4 5 6]]


In [12]:
import numpy as np
x = np.array([11, 12, 13, 14, 15, 60, 70, 80, 90, 100])
print(x)

[ 11  12  13  14  15  60  70  80  90 100]


In [13]:
z = x[np.array([3, 3, 1, 8])] #location values
print(z)

[14 14 12 90]


In [15]:
d = [1, 2, 3, 4, 5]
e = [5, 6, 7, 8, 9]
f = [2, 45, 32, 78, 65]
g = [3, 6, 8, 9, 2]
h = [66, 99, 88, 33, 22]
my_matrices = np.matrix([d, e, f, g, h])
my_matrices

matrix([[ 1,  2,  3,  4,  5],
        [ 5,  6,  7,  8,  9],
        [ 2, 45, 32, 78, 65],
        [ 3,  6,  8,  9,  2],
        [66, 99, 88, 33, 22]])

In [16]:
my_matrices[1:4, 2:5]

matrix([[ 7,  8,  9],
        [32, 78, 65],
        [ 8,  9,  2]])

In [ ]:
my_matrices[2;